version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install time
      - export BUCKET=cfn-pipeline-lambdasqs
      - aws cloudformation package --template-file template.yml --s3-bucket cfn-pipeline-lambdasqs --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
